// let myname = "cristian"


// console.log(myname);

// let mylastname = "benavides"

// console.log(mylastname);

// let myage = 25

// console.log(myage);

// mypet = "Donato"

// console.log(mypet);

// mypetage = 4 

// console.log(mypetage);

// let FullName = `${myname} ${mylastname}`

// console.log(FullName);

// let presentationText = `${myname} ${mylastname} ${myage}  ${mypet} ${mypetage} ${FullName}`

// console.log(presentationText);



// let sumAges = myage + mypetage
// let restAges = myage - mypetage
// let productAges = myage * mypetage
// let divisionAges = myage / mypetage

// console.log(`
// la suma es igual a : ${myage + mypetage}
// la resta es igual a : ${restAges}
// la multiplicacion es igual a : ${productAges}
// la division es igual a : ${divisionAges}

// `);

// // let objeto = {
// //     agua: "liquido",
// //     hielo: "solido",
// //     vapor: "gaseoso",
// //     miEdad: 25,
// //     hombre: true,
// //     objeto2: {
// //         color: "negro",
// //         alto: "1metro",
// //         array1: [1,2,3,4,5,"cristian",
// //        [{
// //         pc: "gamer"
// //        }] 
// //     ] 
// //     }

// // } 
// // console.log(objeto.objeto2.array1[6][0].pc);
// //nivel medio punto 2
// let estudiante = {
//     nombre: "kevin",
//     año: "2do",
//     turno: "mañana",
//     escuela: 23,
//     hombre: true
// }

// console.table (estudiante)
// console.log( `
// ${estudiante.nombre}
// ${estudiante.año}
// ${estudiante.turno}
// ${estudiante.escuela}
// ${estudiante.hombre}`)

// //nivel medio punto 2
// let myPet = {
//     nombre: "thor",
//     edad: "2 años",
//     duerme: "mañana",
//     escuela: 30,
//     macho: true
// }
// console.table (myPet)
// console.log( `
// ${myPet.nombre}
// ${myPet.edad}
// ${myPet.duerme}
// ${myPet.escuela}
// ${myPet.macho}`)

// let fruits = ["banana","strawberry","lemon","pear","apple"]

// console.log(fruits);

// console.log(fruits[0]);
// console.log(fruits[1]);
// console.log(fruits[2]);
// console.log(fruits[3]);
// console.log(fruits[4]);





// let iAmAnAdult = prompt("enter Your Age")  >= 18;

// console.log (`I am an adult: ${iAmAnAdult}`)

// let numbers = [1,2,3,4,5]

// console.log(0);
// console.log(1);
// console.log(2);
// console.log(3);
// console.log(4);

// let family = [
//     {
//         cristian: "crack",
//         kevin: "mayor",
//         celeste: "menor",
//         nicol: "herman del medio"
        
//     },
//     {
//         nombre: "cristian",
//         edad: 105,
        
//     },
//     {
//         nombre: "kevin",
//         edad: 78
//     },
//     {
//         nombre: "celeste",
//         edad: 56
//     },
//     {
//         nombre: "nicol",
//         edad: 38
//     },

    
// ]
// console.log(family);
// console.log(family[0]);
// console.log(family[1]);
// console.log(family[2]);
// console.log(family[3]);
// console.log(family[4]);


// let randomTex = fruits[1] + " " + numbers[3] + " " + family[4].nombre

// console.log(randomTex);

//condicionales
// let numero1 =4
// let numero2 =5

// if (numero1>numero2) {console.log(numero1);
    
// }
// else if  (numero1<numero2) {console.log (numero2); 
// }

// else {console.log("los numeros son iguales");}




// if (numero1 != numero2) {console.log("los numeros no son iguales");
    
// }


// else {console.log("los numeros son iguales");}


let fecha1 = "2018-9-2"
let fecha2 = "2023-7-5"

if (fecha1 < fecha2 ) { console.log(`${fecha2}  es mayor que  ${fecha1}`);
    
}else if {}


